//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ident" type="{}identType"/>
 *         &lt;element name="getBalance" type="{}balanceResponse"/>
 *         &lt;element name="getListFromPointsKOATUU" type="{}pointResponse"/>
 *         &lt;element name="getListToPointsKOATUU" type="{}pointResponse"/>
 *         &lt;element name="getListTripsWithFreePlacesKOATUU" type="{}tripsResponse"/>
 *         &lt;element name="infoTicket" type="{}ticketResponse"/>
 *         &lt;element name="buyTicket" type="{}ticketResponse"/>
 *         &lt;element name="cancelTicket" type="{}cancelResponse"/>
 *         &lt;element name="error" type="{}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ident",
    "getBalance",
    "getListFromPointsKOATUU",
    "getListToPointsKOATUU",
    "getListTripsWithFreePlacesKOATUU",
    "infoTicket",
    "buyTicket",
    "cancelTicket",
    "error"
})
@XmlRootElement(name = "answer")
public class Answer {

    @XmlElement(required = true)
    protected IdentType ident;
    @XmlElement(required = true)
    protected BalanceResponse getBalance;
    @XmlElement(required = true)
    protected PointResponse getListFromPointsKOATUU;
    @XmlElement(required = true)
    protected PointResponse getListToPointsKOATUU;
    @XmlElement(required = true)
    protected TripsResponse getListTripsWithFreePlacesKOATUU;
    @XmlElement(required = true)
    protected TicketResponse infoTicket;
    @XmlElement(required = true)
    protected TicketResponse buyTicket;
    @XmlElement(required = true)
    protected CancelResponse cancelTicket;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link IdentType }
     *     
     */
    public IdentType getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentType }
     *     
     */
    public void setIdent(IdentType value) {
        this.ident = value;
    }

    /**
     * Gets the value of the getBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceResponse }
     *     
     */
    public BalanceResponse getGetBalance() {
        return getBalance;
    }

    /**
     * Sets the value of the getBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceResponse }
     *     
     */
    public void setGetBalance(BalanceResponse value) {
        this.getBalance = value;
    }

    /**
     * Gets the value of the getListFromPointsKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link PointResponse }
     *     
     */
    public PointResponse getGetListFromPointsKOATUU() {
        return getListFromPointsKOATUU;
    }

    /**
     * Sets the value of the getListFromPointsKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointResponse }
     *     
     */
    public void setGetListFromPointsKOATUU(PointResponse value) {
        this.getListFromPointsKOATUU = value;
    }

    /**
     * Gets the value of the getListToPointsKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link PointResponse }
     *     
     */
    public PointResponse getGetListToPointsKOATUU() {
        return getListToPointsKOATUU;
    }

    /**
     * Sets the value of the getListToPointsKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointResponse }
     *     
     */
    public void setGetListToPointsKOATUU(PointResponse value) {
        this.getListToPointsKOATUU = value;
    }

    /**
     * Gets the value of the getListTripsWithFreePlacesKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link TripsResponse }
     *     
     */
    public TripsResponse getGetListTripsWithFreePlacesKOATUU() {
        return getListTripsWithFreePlacesKOATUU;
    }

    /**
     * Sets the value of the getListTripsWithFreePlacesKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link TripsResponse }
     *     
     */
    public void setGetListTripsWithFreePlacesKOATUU(TripsResponse value) {
        this.getListTripsWithFreePlacesKOATUU = value;
    }

    /**
     * Gets the value of the infoTicket property.
     * 
     * @return
     *     possible object is
     *     {@link TicketResponse }
     *     
     */
    public TicketResponse getInfoTicket() {
        return infoTicket;
    }

    /**
     * Sets the value of the infoTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketResponse }
     *     
     */
    public void setInfoTicket(TicketResponse value) {
        this.infoTicket = value;
    }

    /**
     * Gets the value of the buyTicket property.
     * 
     * @return
     *     possible object is
     *     {@link TicketResponse }
     *     
     */
    public TicketResponse getBuyTicket() {
        return buyTicket;
    }

    /**
     * Sets the value of the buyTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketResponse }
     *     
     */
    public void setBuyTicket(TicketResponse value) {
        this.buyTicket = value;
    }

    /**
     * Gets the value of the cancelTicket property.
     * 
     * @return
     *     possible object is
     *     {@link CancelResponse }
     *     
     */
    public CancelResponse getCancelTicket() {
        return cancelTicket;
    }

    /**
     * Sets the value of the cancelTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelResponse }
     *     
     */
    public void setCancelTicket(CancelResponse value) {
        this.cancelTicket = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

}
