//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.04 at 06:56:27 PM EEST 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ident" type="{}identType"/>
 *         &lt;element name="getBalance" type="{}requestType"/>
 *         &lt;element name="getListFromPointsKOATUU" type="{}requestType"/>
 *         &lt;element name="getListToPointsKOATUU" type="{}requestType"/>
 *         &lt;element name="getListTripsWithFreePlacesKOATUU" type="{}requestType"/>
 *         &lt;element name="infoTicket" type="{}buyRequestType"/>
 *         &lt;element name="buyTicket" type="{}buyRequestType"/>
 *         &lt;element name="cancelTicket" type="{}buyRequestType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ident",
    "getBalance",
    "getListFromPointsKOATUU",
    "getListToPointsKOATUU",
    "getListTripsWithFreePlacesKOATUU",
    "infoTicket",
    "buyTicket",
    "cancelTicket",
    "statusTicket"
})
@XmlRootElement(name = "ask")
public class Ask {

    @XmlElement(required = true)
    protected IdentType ident;
    @XmlElement(required = true)
    protected RequestType getBalance;
    @XmlElement(required = true)
    protected RequestType getListFromPointsKOATUU;
    @XmlElement(required = true)
    protected RequestType getListToPointsKOATUU;
    @XmlElement(required = true)
    protected RequestType getListTripsWithFreePlacesKOATUU;
    @XmlElement(required = true)
    protected BuyRequestType infoTicket;
    @XmlElement(required = true)
    protected BuyRequestType buyTicket;
    @XmlElement(required = true)
    protected BuyRequestType cancelTicket;
    @XmlElement(required = true)
    protected BuyRequestType statusTicket;

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link IdentType }
     *     
     */
    public IdentType getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentType }
     *     
     */
    public void setIdent(IdentType value) {
        this.ident = value;
    }

    /**
     * Gets the value of the getBalance property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getGetBalance() {
        return getBalance;
    }

    /**
     * Sets the value of the getBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setGetBalance(RequestType value) {
        this.getBalance = value;
    }

    /**
     * Gets the value of the getListFromPointsKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getGetListFromPointsKOATUU() {
        return getListFromPointsKOATUU;
    }

    /**
     * Sets the value of the getListFromPointsKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setGetListFromPointsKOATUU(RequestType value) {
        this.getListFromPointsKOATUU = value;
    }

    /**
     * Gets the value of the getListToPointsKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getGetListToPointsKOATUU() {
        return getListToPointsKOATUU;
    }

    /**
     * Sets the value of the getListToPointsKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setGetListToPointsKOATUU(RequestType value) {
        this.getListToPointsKOATUU = value;
    }

    /**
     * Gets the value of the getListTripsWithFreePlacesKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getGetListTripsWithFreePlacesKOATUU() {
        return getListTripsWithFreePlacesKOATUU;
    }

    /**
     * Sets the value of the getListTripsWithFreePlacesKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setGetListTripsWithFreePlacesKOATUU(RequestType value) {
        this.getListTripsWithFreePlacesKOATUU = value;
    }

    /**
     * Gets the value of the infoTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BuyRequestType }
     *     
     */
    public BuyRequestType getInfoTicket() {
        return infoTicket;
    }

    /**
     * Sets the value of the infoTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyRequestType }
     *     
     */
    public void setInfoTicket(BuyRequestType value) {
        this.infoTicket = value;
    }

    /**
     * Gets the value of the buyTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BuyRequestType }
     *     
     */
    public BuyRequestType getBuyTicket() {
        return buyTicket;
    }

    /**
     * Sets the value of the buyTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyRequestType }
     *     
     */
    public void setBuyTicket(BuyRequestType value) {
        this.buyTicket = value;
    }

    /**
     * Gets the value of the cancelTicket property.
     * 
     * @return
     *     possible object is
     *     {@link BuyRequestType }
     *     
     */
    public BuyRequestType getCancelTicket() {
        return cancelTicket;
    }

    /**
     * Sets the value of the cancelTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyRequestType }
     *     
     */
    public void setCancelTicket(BuyRequestType value) {
        this.cancelTicket = value;
    }

	public BuyRequestType getStatusTicket() {
		return statusTicket;
	}

	public void setStatusTicket(BuyRequestType statusTicket) {
		this.statusTicket = statusTicket;
	}
    
}
