//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gillsoft.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gillsoft.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TechInfoType }
     * 
     */
    public TechInfoType createTechInfoType() {
        return new TechInfoType();
    }

    /**
     * Create an instance of {@link BuyRequestType }
     * 
     */
    public BuyRequestType createBuyRequestType() {
        return new BuyRequestType();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link Point.Location }
     * 
     */
    public Point.Location createPointLocation() {
        return new Point.Location();
    }

    /**
     * Create an instance of {@link CancelResponse }
     * 
     */
    public CancelResponse createCancelResponse() {
        return new CancelResponse();
    }

    /**
     * Create an instance of {@link CancelResponse.ReturnStatement }
     * 
     */
    public CancelResponse.ReturnStatement createCancelResponseReturnStatement() {
        return new CancelResponse.ReturnStatement();
    }

    /**
     * Create an instance of {@link CancelResponse.ReturnStatement.RulesReturn }
     * 
     */
    public CancelResponse.ReturnStatement.RulesReturn createCancelResponseReturnStatementRulesReturn() {
        return new CancelResponse.ReturnStatement.RulesReturn();
    }

    /**
     * Create an instance of {@link TicketResponse }
     * 
     */
    public TicketResponse createTicketResponse() {
        return new TicketResponse();
    }

    /**
     * Create an instance of {@link TicketResponse.Ticket }
     * 
     */
    public TicketResponse.Ticket createTicketResponseTicket() {
        return new TicketResponse.Ticket();
    }

    /**
     * Create an instance of {@link TripsResponse }
     * 
     */
    public TripsResponse createTripsResponse() {
        return new TripsResponse();
    }

    /**
     * Create an instance of {@link TripsResponse.Trip }
     * 
     */
    public TripsResponse.Trip createTripsResponseTrip() {
        return new TripsResponse.Trip();
    }

    /**
     * Create an instance of {@link BalanceResponse }
     * 
     */
    public BalanceResponse createBalanceResponse() {
        return new BalanceResponse();
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link IdentType }
     * 
     */
    public IdentType createIdentType() {
        return new IdentType();
    }

    /**
     * Create an instance of {@link PointResponse }
     * 
     */
    public PointResponse createPointResponse() {
        return new PointResponse();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link MoneyType }
     * 
     */
    public MoneyType createMoneyType() {
        return new MoneyType();
    }

    /**
     * Create an instance of {@link PricePart }
     * 
     */
    public PricePart createPricePart() {
        return new PricePart();
    }

    /**
     * Create an instance of {@link TripPoint }
     * 
     */
    public TripPoint createTripPoint() {
        return new TripPoint();
    }

    /**
     * Create an instance of {@link TripTime }
     * 
     */
    public TripTime createTripTime() {
        return new TripTime();
    }

    /**
     * Create an instance of {@link TechInfoType.Client }
     * 
     */
    public TechInfoType.Client createTechInfoTypeClient() {
        return new TechInfoType.Client();
    }

    /**
     * Create an instance of {@link BuyRequestType.Ticket }
     * 
     */
    public BuyRequestType.Ticket createBuyRequestTypeTicket() {
        return new BuyRequestType.Ticket();
    }

    /**
     * Create an instance of {@link Point.Location.Item }
     * 
     */
    public Point.Location.Item createPointLocationItem() {
        return new Point.Location.Item();
    }

    /**
     * Create an instance of {@link CancelResponse.ReturnStatement.RulesReturn.Rule }
     * 
     */
    public CancelResponse.ReturnStatement.RulesReturn.Rule createCancelResponseReturnStatementRulesReturnRule() {
        return new CancelResponse.ReturnStatement.RulesReturn.Rule();
    }

    /**
     * Create an instance of {@link TicketResponse.Seats }
     * 
     */
    public TicketResponse.Seats createTicketResponseSeats() {
        return new TicketResponse.Seats();
    }

    /**
     * Create an instance of {@link TicketResponse.Ticket.AsUID }
     * 
     */
    public TicketResponse.Ticket.AsUID createTicketResponseTicketAsUID() {
        return new TicketResponse.Ticket.AsUID();
    }

    /**
     * Create an instance of {@link TicketResponse.Ticket.Round }
     * 
     */
    public TicketResponse.Ticket.Round createTicketResponseTicketRound() {
        return new TicketResponse.Ticket.Round();
    }

    /**
     * Create an instance of {@link TicketResponse.Ticket.Place }
     * 
     */
    public TicketResponse.Ticket.Place createTicketResponseTicketPlace() {
        return new TicketResponse.Ticket.Place();
    }

    /**
     * Create an instance of {@link TripsResponse.Trip.Round }
     * 
     */
    public TripsResponse.Trip.Round createTripsResponseTripRound() {
        return new TripsResponse.Trip.Round();
    }

    /**
     * Create an instance of {@link BalanceResponse.Balance }
     * 
     */
    public BalanceResponse.Balance createBalanceResponseBalance() {
        return new BalanceResponse.Balance();
    }

}
