//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for point complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="point">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="name_ua" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name_ru" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name_en" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="kod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="country" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name_ua" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name_ru" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name_en" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "point", propOrder = {
    "location"
})
public class Point implements Serializable {

	private static final long serialVersionUID = -5456081449764009529L;
	
	@XmlElement(required = true)
    protected Point.Location location;
    @XmlAttribute(name = "kod")
    protected String kod;
    @XmlAttribute(name = "country")
    protected String country;
    @XmlAttribute(name = "name_ua")
    protected String nameUa;
    @XmlAttribute(name = "name_ru")
    protected String nameRu;
    @XmlAttribute(name = "name_en")
    protected String nameEn;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Point.Location }
     *     
     */
    public Point.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point.Location }
     *     
     */
    public void setLocation(Point.Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the kod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKod() {
        return kod;
    }

    /**
     * Sets the value of the kod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKod(String value) {
        this.kod = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the nameUa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameUa() {
        return nameUa;
    }

    /**
     * Sets the value of the nameUa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameUa(String value) {
        this.nameUa = value;
    }

    /**
     * Gets the value of the nameRu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRu() {
        return nameRu;
    }

    /**
     * Sets the value of the nameRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRu(String value) {
        this.nameRu = value;
    }

    /**
     * Gets the value of the nameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * Sets the value of the nameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEn(String value) {
        this.nameEn = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="name_ua" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name_ru" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name_en" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class Location implements Serializable {

		private static final long serialVersionUID = -2482720828766155826L;
		
		protected List<Point.Location.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Point.Location.Item }
         * 
         * 
         */
        public List<Point.Location.Item> getItem() {
            if (item == null) {
                item = new ArrayList<Point.Location.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="level" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="name_ua" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name_ru" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name_en" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Item implements Serializable {

			private static final long serialVersionUID = -1028405392453431208L;
			
			@XmlValue
            protected String value;
            @XmlAttribute(name = "level")
            protected Byte level;
            @XmlAttribute(name = "name_ua")
            protected String nameUa;
            @XmlAttribute(name = "name_ru")
            protected String nameRu;
            @XmlAttribute(name = "name_en")
            protected String nameEn;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the level property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getLevel() {
                return level;
            }

            /**
             * Sets the value of the level property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setLevel(Byte value) {
                this.level = value;
            }

            /**
             * Gets the value of the nameUa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameUa() {
                return nameUa;
            }

            /**
             * Sets the value of the nameUa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameUa(String value) {
                this.nameUa = value;
            }

            /**
             * Gets the value of the nameRu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameRu() {
                return nameRu;
            }

            /**
             * Sets the value of the nameRu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameRu(String value) {
                this.nameRu = value;
            }

            /**
             * Gets the value of the nameEn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameEn() {
                return nameEn;
            }

            /**
             * Sets the value of the nameEn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameEn(String value) {
                this.nameEn = value;
            }

        }

    }

}
