//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pointResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pointResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="techInfo" type="{}techInfoType"/>
 *         &lt;element name="FromPointKOATUU" type="{}point" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ToPointKOATUU" type="{}point" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="error" type="{}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pointResponse", propOrder = {
    "techInfo",
    "fromPointKOATUU",
    "toPointKOATUU",
    "error"
})
public class PointResponse extends BaseResponse {
	
	@XmlElement(required = true)
    protected TechInfoType techInfo;
    @XmlElement(name = "FromPointKOATUU")
    protected List<Point> fromPointKOATUU;
    @XmlElement(name = "ToPointKOATUU")
    protected List<Point> toPointKOATUU;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the techInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TechInfoType }
     *     
     */
    public TechInfoType getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechInfoType }
     *     
     */
    public void setTechInfo(TechInfoType value) {
        this.techInfo = value;
    }

    /**
     * Gets the value of the fromPointKOATUU property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fromPointKOATUU property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFromPointKOATUU().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getFromPointKOATUU() {
        if (fromPointKOATUU == null) {
            fromPointKOATUU = new ArrayList<Point>();
        }
        return this.fromPointKOATUU;
    }

    /**
     * Gets the value of the toPointKOATUU property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toPointKOATUU property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToPointKOATUU().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getToPointKOATUU() {
        if (toPointKOATUU == null) {
            toPointKOATUU = new ArrayList<Point>();
        }
        return this.toPointKOATUU;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

}
