//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.18 at 10:32:32 AM EEST 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="techInfo" type="{}techInfoType"/>
 *         &lt;element name="FromPointKOATUU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ToPointKOATUU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="daysForward" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regularity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeToDep" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requiredInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = {
    "techInfo",
    "fromPointKOATUU",
    "toPointKOATUU",
    "date",
    "daysForward",
    "regularity",
    "price",
    "timeToDep",
    "requiredInfo",
    "carrier"
})
public class RequestType {

    @XmlElement(required = true)
    protected TechInfoType techInfo;
    @XmlElement(name = "FromPointKOATUU", required = true)
    protected String fromPointKOATUU;
    @XmlElement(name = "ToPointKOATUU", required = true)
    protected String toPointKOATUU;
    @XmlElement(required = true)
    protected String date;
    @XmlElement(required = true)
    protected String daysForward;
    @XmlElement(required = true)
    protected String regularity;
    @XmlElement(required = true)
    protected String price;
    @XmlElement(required = true)
    protected String timeToDep;
    @XmlElement(required = true)
    protected String requiredInfo;
    @XmlElement(required = true)
    protected String carrier;

    /**
     * Gets the value of the techInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TechInfoType }
     *     
     */
    public TechInfoType getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechInfoType }
     *     
     */
    public void setTechInfo(TechInfoType value) {
        this.techInfo = value;
    }

    /**
     * Gets the value of the fromPointKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromPointKOATUU() {
        return fromPointKOATUU;
    }

    /**
     * Sets the value of the fromPointKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromPointKOATUU(String value) {
        this.fromPointKOATUU = value;
    }

    /**
     * Gets the value of the toPointKOATUU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToPointKOATUU() {
        return toPointKOATUU;
    }

    /**
     * Sets the value of the toPointKOATUU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToPointKOATUU(String value) {
        this.toPointKOATUU = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the daysForward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysForward() {
        return daysForward;
    }

    /**
     * Sets the value of the daysForward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysForward(String value) {
        this.daysForward = value;
    }

    /**
     * Gets the value of the regularity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegularity() {
        return regularity;
    }

    /**
     * Sets the value of the regularity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegularity(String value) {
        this.regularity = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrice(String value) {
        this.price = value;
    }

    /**
     * Gets the value of the timeToDep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeToDep() {
        return timeToDep;
    }

    /**
     * Sets the value of the timeToDep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeToDep(String value) {
        this.timeToDep = value;
    }

    /**
     * Gets the value of the requiredInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredInfo() {
        return requiredInfo;
    }

    /**
     * Sets the value of the requiredInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredInfo(String value) {
        this.requiredInfo = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

}
