//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for techInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="techInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="client">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="agent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="workplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="answerAuthor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "techInfoType", propOrder = {
    "client",
    "answerAuthor"
})
public class TechInfoType {

	@XmlElement(required = true)
    protected TechInfoType.Client client;
    @XmlElement(required = true)
    protected String answerAuthor;

    /**
     * Gets the value of the client property.
     * 
     * @return
     *     possible object is
     *     {@link TechInfoType.Client }
     *     
     */
    public TechInfoType.Client getClient() {
        return client;
    }

    /**
     * Sets the value of the client property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechInfoType.Client }
     *     
     */
    public void setClient(TechInfoType.Client value) {
        this.client = value;
    }

    /**
     * Gets the value of the answerAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswerAuthor() {
        return answerAuthor;
    }

    /**
     * Sets the value of the answerAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswerAuthor(String value) {
        this.answerAuthor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="agent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="workplace" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "agent",
        "workplace",
        "uid"
    })
    public static class Client {
		
		@XmlElement(required = true)
        protected String agent;
        @XmlElement(required = true)
        protected String workplace;
        @XmlElement(required = true)
        protected String uid;

        /**
         * Gets the value of the agent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAgent() {
            return agent;
        }

        /**
         * Sets the value of the agent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAgent(String value) {
            this.agent = value;
        }

        /**
         * Gets the value of the workplace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkplace() {
            return workplace;
        }

        /**
         * Sets the value of the workplace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkplace(String value) {
            this.workplace = value;
        }

        /**
         * Gets the value of the uid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUid() {
            return uid;
        }

        /**
         * Sets the value of the uid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUid(String value) {
            this.uid = value;
        }

    }

}
