//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ticketResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ticketResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="techInfo" type="{}techInfoType"/>
 *         &lt;element name="Ticket" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AsUID">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="askod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Round">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PointFrom" type="{}tripPoint"/>
 *                             &lt;element name="PointTo" type="{}tripPoint"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PointFrom" type="{}tripPoint"/>
 *                   &lt;element name="PointTo" type="{}tripPoint"/>
 *                   &lt;element name="TimeDeparture" type="{}tripTime"/>
 *                   &lt;element name="TimeArrival" type="{}tripTime"/>
 *                   &lt;element name="Place">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="insurance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="money" type="{}moneyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="seats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="seat" type="{http://www.w3.org/2001/XMLSchema}byte" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="error" type="{}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ticketResponse", propOrder = {
    "techInfo",
    "ticket",
    "seats",
    "error"
})
public class TicketResponse extends BaseResponse implements Serializable {

	private static final long serialVersionUID = 867881896465325210L;
	
	@XmlElement(required = true)
    protected TechInfoType techInfo;
    @XmlElement(name = "Ticket")
    protected List<TicketResponse.Ticket> ticket;
    @XmlElement(required = true)
    protected TicketResponse.Seats seats;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the techInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TechInfoType }
     *     
     */
    public TechInfoType getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechInfoType }
     *     
     */
    public void setTechInfo(TechInfoType value) {
        this.techInfo = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ticket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTicket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TicketResponse.Ticket }
     * 
     * 
     */
    public List<TicketResponse.Ticket> getTicket() {
        if (ticket == null) {
            ticket = new ArrayList<TicketResponse.Ticket>();
        }
        return this.ticket;
    }

    /**
     * Gets the value of the seats property.
     * 
     * @return
     *     possible object is
     *     {@link TicketResponse.Seats }
     *     
     */
    public TicketResponse.Seats getSeats() {
        return seats;
    }

    /**
     * Sets the value of the seats property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketResponse.Seats }
     *     
     */
    public void setSeats(TicketResponse.Seats value) {
        this.seats = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="seat" type="{http://www.w3.org/2001/XMLSchema}byte" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "seat"
    })
    public static class Seats implements Serializable {

		private static final long serialVersionUID = -8734754521268194720L;
		
		@XmlElement(type = Byte.class)
        protected List<Byte> seat;

        /**
         * Gets the value of the seat property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the seat property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Byte }
         * 
         * 
         */
        public List<Byte> getSeat() {
            if (seat == null) {
                seat = new ArrayList<Byte>();
            }
            return this.seat;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AsUID">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="askod" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Round">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PointFrom" type="{}tripPoint"/>
     *                   &lt;element name="PointTo" type="{}tripPoint"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PointFrom" type="{}tripPoint"/>
     *         &lt;element name="PointTo" type="{}tripPoint"/>
     *         &lt;element name="TimeDeparture" type="{}tripTime"/>
     *         &lt;element name="TimeArrival" type="{}tripTime"/>
     *         &lt;element name="Place">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="insurance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="money" type="{}moneyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uid",
        "asUID",
        "round",
        "pointFrom",
        "pointTo",
        "timeDeparture",
        "timeArrival",
        "place",
        "insurance",
        "carrier",
        "distance",
        "money"
    })
    public static class Ticket implements Serializable {

		private static final long serialVersionUID = 7443100574022980787L;
		
		@XmlElement(required = true)
        protected String uid;
        @XmlElement(name = "AsUID", required = true)
        protected TicketResponse.Ticket.AsUID asUID;
        @XmlElement(name = "Round", required = true)
        protected TicketResponse.Ticket.Round round;
        @XmlElement(name = "PointFrom", required = true)
        protected TripPoint pointFrom;
        @XmlElement(name = "PointTo", required = true)
        protected TripPoint pointTo;
        @XmlElement(name = "TimeDeparture", required = true)
        protected TripTime timeDeparture;
        @XmlElement(name = "TimeArrival", required = true)
        protected TripTime timeArrival;
        @XmlElement(name = "Place", required = true)
        protected TicketResponse.Ticket.Place place;
        @XmlElement(required = true)
        protected String insurance;
        @XmlElement(required = true)
        protected String carrier;
        @XmlElement(required = true)
        protected BigDecimal distance;
        @XmlElement(required = true)
        protected MoneyType money;

        /**
         * Gets the value of the uid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUid() {
            return uid;
        }

        /**
         * Sets the value of the uid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUid(String value) {
            this.uid = value;
        }

        /**
         * Gets the value of the asUID property.
         * 
         * @return
         *     possible object is
         *     {@link TicketResponse.Ticket.AsUID }
         *     
         */
        public TicketResponse.Ticket.AsUID getAsUID() {
            return asUID;
        }

        /**
         * Sets the value of the asUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketResponse.Ticket.AsUID }
         *     
         */
        public void setAsUID(TicketResponse.Ticket.AsUID value) {
            this.asUID = value;
        }

        /**
         * Gets the value of the round property.
         * 
         * @return
         *     possible object is
         *     {@link TicketResponse.Ticket.Round }
         *     
         */
        public TicketResponse.Ticket.Round getRound() {
            return round;
        }

        /**
         * Sets the value of the round property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketResponse.Ticket.Round }
         *     
         */
        public void setRound(TicketResponse.Ticket.Round value) {
            this.round = value;
        }

        /**
         * Gets the value of the pointFrom property.
         * 
         * @return
         *     possible object is
         *     {@link TripPoint }
         *     
         */
        public TripPoint getPointFrom() {
            return pointFrom;
        }

        /**
         * Sets the value of the pointFrom property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripPoint }
         *     
         */
        public void setPointFrom(TripPoint value) {
            this.pointFrom = value;
        }

        /**
         * Gets the value of the pointTo property.
         * 
         * @return
         *     possible object is
         *     {@link TripPoint }
         *     
         */
        public TripPoint getPointTo() {
            return pointTo;
        }

        /**
         * Sets the value of the pointTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripPoint }
         *     
         */
        public void setPointTo(TripPoint value) {
            this.pointTo = value;
        }

        /**
         * Gets the value of the timeDeparture property.
         * 
         * @return
         *     possible object is
         *     {@link TripTime }
         *     
         */
        public TripTime getTimeDeparture() {
            return timeDeparture;
        }

        /**
         * Sets the value of the timeDeparture property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripTime }
         *     
         */
        public void setTimeDeparture(TripTime value) {
            this.timeDeparture = value;
        }

        /**
         * Gets the value of the timeArrival property.
         * 
         * @return
         *     possible object is
         *     {@link TripTime }
         *     
         */
        public TripTime getTimeArrival() {
            return timeArrival;
        }

        /**
         * Sets the value of the timeArrival property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripTime }
         *     
         */
        public void setTimeArrival(TripTime value) {
            this.timeArrival = value;
        }

        /**
         * Gets the value of the place property.
         * 
         * @return
         *     possible object is
         *     {@link TicketResponse.Ticket.Place }
         *     
         */
        public TicketResponse.Ticket.Place getPlace() {
            return place;
        }

        /**
         * Sets the value of the place property.
         * 
         * @param value
         *     allowed object is
         *     {@link TicketResponse.Ticket.Place }
         *     
         */
        public void setPlace(TicketResponse.Ticket.Place value) {
            this.place = value;
        }

        /**
         * Gets the value of the insurance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInsurance() {
            return insurance;
        }

        /**
         * Sets the value of the insurance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInsurance(String value) {
            this.insurance = value;
        }

        /**
         * Gets the value of the carrier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCarrier() {
            return carrier;
        }

        /**
         * Sets the value of the carrier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCarrier(String value) {
            this.carrier = value;
        }

        /**
         * Gets the value of the distance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDistance() {
            return distance;
        }

        /**
         * Sets the value of the distance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDistance(BigDecimal value) {
            this.distance = value;
        }

        /**
         * Gets the value of the money property.
         * 
         * @return
         *     possible object is
         *     {@link MoneyType }
         *     
         */
        public MoneyType getMoney() {
            return money;
        }

        /**
         * Sets the value of the money property.
         * 
         * @param value
         *     allowed object is
         *     {@link MoneyType }
         *     
         */
        public void setMoney(MoneyType value) {
            this.money = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="askod" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AsUID implements Serializable {

			private static final long serialVersionUID = -5127266177486575593L;
			
			@XmlValue
            protected String value;
            @XmlAttribute(name = "askod")
            protected String askod;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the askod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAskod() {
                return askod;
            }

            /**
             * Sets the value of the askod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAskod(String value) {
                this.askod = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Place implements Serializable {

			private static final long serialVersionUID = 3707031104050628869L;
			
			@XmlValue
            protected String value;
            @XmlAttribute(name = "className")
            protected String className;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the className property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClassName() {
                return className;
            }

            /**
             * Sets the value of the className property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClassName(String value) {
                this.className = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PointFrom" type="{}tripPoint"/>
         *         &lt;element name="PointTo" type="{}tripPoint"/>
         *       &lt;/sequence>
         *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pointFrom",
            "pointTo"
        })
        public static class Round implements Serializable {

			private static final long serialVersionUID = 1233716434399794957L;
			
			@XmlElement(name = "PointFrom", required = true)
            protected TripPoint pointFrom;
            @XmlElement(name = "PointTo", required = true)
            protected TripPoint pointTo;
            @XmlAttribute(name = "num")
            protected String num;

            /**
             * Gets the value of the pointFrom property.
             * 
             * @return
             *     possible object is
             *     {@link TripPoint }
             *     
             */
            public TripPoint getPointFrom() {
                return pointFrom;
            }

            /**
             * Sets the value of the pointFrom property.
             * 
             * @param value
             *     allowed object is
             *     {@link TripPoint }
             *     
             */
            public void setPointFrom(TripPoint value) {
                this.pointFrom = value;
            }

            /**
             * Gets the value of the pointTo property.
             * 
             * @return
             *     possible object is
             *     {@link TripPoint }
             *     
             */
            public TripPoint getPointTo() {
                return pointTo;
            }

            /**
             * Sets the value of the pointTo property.
             * 
             * @param value
             *     allowed object is
             *     {@link TripPoint }
             *     
             */
            public void setPointTo(TripPoint value) {
                this.pointTo = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
