//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.17 at 01:13:55 PM EEST 
//


package com.gillsoft.client;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for tripsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tripsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="techInfo" type="{}techInfoType"/>
 *         &lt;element name="trip" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Round">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="regularity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="bus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="ArrFromPoint" type="{}tripTime"/>
 *                   &lt;element name="DepFromPoint" type="{}tripTime"/>
 *                   &lt;element name="ArrToPoint" type="{}tripTime"/>
 *                   &lt;element name="DepToPoint" type="{}tripTime"/>
 *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="freePlaces" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="lastUpdate" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="FromPoint" type="{}tripPoint"/>
 *                   &lt;element name="ToPoint" type="{}tripPoint"/>
 *                   &lt;element name="Server" type="{}tripPoint"/>
 *                   &lt;element name="tib" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="requiredInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="error" type="{}errorType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tripsResponse", propOrder = {
    "techInfo",
    "trip",
    "error"
})
public class TripsResponse extends BaseResponse {

	@XmlElement(required = true)
    protected TechInfoType techInfo;
    protected List<TripsResponse.Trip> trip;
    @XmlElement(required = true)
    protected ErrorType error;

    /**
     * Gets the value of the techInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TechInfoType }
     *     
     */
    public TechInfoType getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechInfoType }
     *     
     */
    public void setTechInfo(TechInfoType value) {
        this.techInfo = value;
    }

    /**
     * Gets the value of the trip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TripsResponse.Trip }
     * 
     * 
     */
    public List<TripsResponse.Trip> getTrip() {
        if (trip == null) {
            trip = new ArrayList<TripsResponse.Trip>();
        }
        return this.trip;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Round">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="regularity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="bus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="ArrFromPoint" type="{}tripTime"/>
     *         &lt;element name="DepFromPoint" type="{}tripTime"/>
     *         &lt;element name="ArrToPoint" type="{}tripTime"/>
     *         &lt;element name="DepToPoint" type="{}tripTime"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="freePlaces" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="lastUpdate" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="FromPoint" type="{}tripPoint"/>
     *         &lt;element name="ToPoint" type="{}tripPoint"/>
     *         &lt;element name="Server" type="{}tripPoint"/>
     *         &lt;element name="tib" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="requiredInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "round",
        "regularity",
        "bus",
        "distance",
        "arrFromPoint",
        "depFromPoint",
        "arrToPoint",
        "depToPoint",
        "date",
        "price",
        "freePlaces",
        "lastUpdate",
        "fromPoint",
        "toPoint",
        "server",
        "tib",
        "requiredInfo",
        "carrier"
    })
    public static class Trip implements Serializable {

		private static final long serialVersionUID = 7963763003723033716L;
		
		@XmlElement(name = "Round", required = true)
        protected TripsResponse.Trip.Round round;
        protected byte regularity;
        @XmlElement(required = true)
        protected String bus;
        @XmlElement(required = true)
        protected BigDecimal distance;
        @XmlElement(name = "ArrFromPoint", required = true)
        protected TripTime arrFromPoint;
        @XmlElement(name = "DepFromPoint", required = true)
        protected TripTime depFromPoint;
        @XmlElement(name = "ArrToPoint", required = true)
        protected TripTime arrToPoint;
        @XmlElement(name = "DepToPoint", required = true)
        protected TripTime depToPoint;
        @XmlElement(required = true)
        protected String date;
        @XmlElement(required = true)
        protected BigDecimal price;
        protected byte freePlaces;
        protected long lastUpdate;
        @XmlElement(name = "FromPoint", required = true)
        protected TripPoint fromPoint;
        @XmlElement(name = "ToPoint", required = true)
        protected TripPoint toPoint;
        @XmlElement(name = "Server", required = true)
        protected TripPoint server;
        @XmlElement(required = true)
        protected String tib;
        @XmlElement(required = true)
        protected String requiredInfo;
        @XmlElement(required = true)
        protected String carrier;

        /**
         * Gets the value of the round property.
         * 
         * @return
         *     possible object is
         *     {@link TripsResponse.Trip.Round }
         *     
         */
        public TripsResponse.Trip.Round getRound() {
            return round;
        }

        /**
         * Sets the value of the round property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripsResponse.Trip.Round }
         *     
         */
        public void setRound(TripsResponse.Trip.Round value) {
            this.round = value;
        }

        /**
         * Gets the value of the regularity property.
         * 
         */
        public byte getRegularity() {
            return regularity;
        }

        /**
         * Sets the value of the regularity property.
         * 
         */
        public void setRegularity(byte value) {
            this.regularity = value;
        }

        /**
         * Gets the value of the bus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBus() {
            return bus;
        }

        /**
         * Sets the value of the bus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBus(String value) {
            this.bus = value;
        }

        /**
         * Gets the value of the distance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDistance() {
            return distance;
        }

        /**
         * Sets the value of the distance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDistance(BigDecimal value) {
            this.distance = value;
        }

        /**
         * Gets the value of the arrFromPoint property.
         * 
         * @return
         *     possible object is
         *     {@link TripTime }
         *     
         */
        public TripTime getArrFromPoint() {
            return arrFromPoint;
        }

        /**
         * Sets the value of the arrFromPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripTime }
         *     
         */
        public void setArrFromPoint(TripTime value) {
            this.arrFromPoint = value;
        }

        /**
         * Gets the value of the depFromPoint property.
         * 
         * @return
         *     possible object is
         *     {@link TripTime }
         *     
         */
        public TripTime getDepFromPoint() {
            return depFromPoint;
        }

        /**
         * Sets the value of the depFromPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripTime }
         *     
         */
        public void setDepFromPoint(TripTime value) {
            this.depFromPoint = value;
        }

        /**
         * Gets the value of the arrToPoint property.
         * 
         * @return
         *     possible object is
         *     {@link TripTime }
         *     
         */
        public TripTime getArrToPoint() {
            return arrToPoint;
        }

        /**
         * Sets the value of the arrToPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripTime }
         *     
         */
        public void setArrToPoint(TripTime value) {
            this.arrToPoint = value;
        }

        /**
         * Gets the value of the depToPoint property.
         * 
         * @return
         *     possible object is
         *     {@link TripTime }
         *     
         */
        public TripTime getDepToPoint() {
            return depToPoint;
        }

        /**
         * Sets the value of the depToPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripTime }
         *     
         */
        public void setDepToPoint(TripTime value) {
            this.depToPoint = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrice(BigDecimal value) {
            this.price = value;
        }

        /**
         * Gets the value of the freePlaces property.
         * 
         */
        public byte getFreePlaces() {
            return freePlaces;
        }

        /**
         * Sets the value of the freePlaces property.
         * 
         */
        public void setFreePlaces(byte value) {
            this.freePlaces = value;
        }

        /**
         * Gets the value of the lastUpdate property.
         * 
         */
        public long getLastUpdate() {
            return lastUpdate;
        }

        /**
         * Sets the value of the lastUpdate property.
         * 
         */
        public void setLastUpdate(long value) {
            this.lastUpdate = value;
        }

        /**
         * Gets the value of the fromPoint property.
         * 
         * @return
         *     possible object is
         *     {@link TripPoint }
         *     
         */
        public TripPoint getFromPoint() {
            return fromPoint;
        }

        /**
         * Sets the value of the fromPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripPoint }
         *     
         */
        public void setFromPoint(TripPoint value) {
            this.fromPoint = value;
        }

        /**
         * Gets the value of the toPoint property.
         * 
         * @return
         *     possible object is
         *     {@link TripPoint }
         *     
         */
        public TripPoint getToPoint() {
            return toPoint;
        }

        /**
         * Sets the value of the toPoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripPoint }
         *     
         */
        public void setToPoint(TripPoint value) {
            this.toPoint = value;
        }

        /**
         * Gets the value of the server property.
         * 
         * @return
         *     possible object is
         *     {@link TripPoint }
         *     
         */
        public TripPoint getServer() {
            return server;
        }

        /**
         * Sets the value of the server property.
         * 
         * @param value
         *     allowed object is
         *     {@link TripPoint }
         *     
         */
        public void setServer(TripPoint value) {
            this.server = value;
        }

        /**
         * Gets the value of the tib property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTib() {
            return tib;
        }

        /**
         * Sets the value of the tib property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTib(String value) {
            this.tib = value;
        }

        /**
         * Gets the value of the requiredInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequiredInfo() {
            return requiredInfo;
        }

        /**
         * Sets the value of the requiredInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequiredInfo(String value) {
            this.requiredInfo = value;
        }
        
        /**
        * Gets the value of the carrier property.
        * 
        * @return
        *     possible object is
        *     {@link String }
        *     
        */
       public String getCarrier() {
           return carrier;
       }

       /**
        * Sets the value of the carrier property.
        * 
        * @param value
        *     allowed object is
        *     {@link String }
        *     
        */
       public void setCarrier(String value) {
           this.carrier = value;
       }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Round implements Serializable {

			private static final long serialVersionUID = 2933046028044089247L;
			
			@XmlValue
            protected String value;
            @XmlAttribute(name = "num")
            protected String num;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
